// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as mqtt$0 from "../../../../../mqttc/internal/mqtt/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "messages:batch": mqtt$0.MessagesBatch;
            "state:changed": mqtt$0.StateChanged;
            "subscriptions:changed": mqtt$0.SubscriptionsChanged;
            "topics:changed": mqtt$0.TopicsChanged;
        }
    }
}
