// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";

/**
 * Profile is a stored broker connection. Password is write-only: the UI sends
 * it on Save and it goes straight to the SecretStore; List/Get never return
 * it. HasPassword tells the UI whether one is stored.
 */
export interface Profile {
    "id": string;
    "name": string;

    /**
     * tcp://host:1883
     */
    "broker": string;
    "clientId": string;
    "username": string;

    /**
     * write-only, never persisted to disk
     */
    "password"?: string;
    "hasPassword": boolean;
    "cleanStart": boolean;

    /**
     * skip TLS verify (dev brokers)
     */
    "insecure": boolean;
}

/**
 * Snapshot is the single startup payload: everything the UI needs to render
 * from scratch. Sessions only lists profiles that have a session; the UI
 * treats the rest as disconnected.
 */
export interface Snapshot {
    "profiles": Profile[] | null;
    "sessions": mqtt$0.SessionSnapshot[] | null;
}
