// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1568082, id);
}

export function Get(id: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(3631424447, id);
}

export function List(): $CancellablePromise<$models.Profile[] | null> {
    return $Call.ByID(1754540505);
}

/**
 * Save creates (empty ID) or updates. An empty Password on update keeps the
 * stored one. Returns the stored profile (without the password).
 */
export function Save(p: $models.Profile): $CancellablePromise<$models.Profile> {
    return $Call.ByID(154566688, p);
}
