// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the RPC façade the frontend calls. All lifecycle logic
 * lives in sessionManager; this type only adapts signatures for Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../mqtt/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear forgets history for one topic, or everything when topic is "".
 */
export function Clear(profileID: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(2742274221, profileID, topic);
}

export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1719021526, profileID);
}

export function Disconnect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1808465978, profileID);
}

export function Publish(profileID: string, pub: mqtt$0.Publish): $CancellablePromise<void> {
    return $Call.ByID(2031988939, profileID, pub);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2582991380);
}

export function Subscribe(profileID: string, sub: mqtt$0.Subscription): $CancellablePromise<void> {
    return $Call.ByID(1292370152, profileID, sub);
}

export function Unsubscribe(profileID: string, filter: string): $CancellablePromise<void> {
    return $Call.ByID(3256548877, profileID, filter);
}

export function Unwatch(profileID: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(3746840754, profileID, topic);
}

/**
 * Watch starts streaming topic for profileID and returns its history.
 */
export function Watch(profileID: string, topic: string, limit: number): $CancellablePromise<mqtt$0.WatchResult> {
    return $Call.ByID(1718914059, profileID, topic, limit);
}
