// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnState is the only source of truth for a session's status. Transitions
 * are enforced in session.go; the frontend mirrors this enum exactly.
 */
export enum ConnState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateDisconnected = "disconnected",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateReconnecting = "reconnecting",

    /**
     * terminal until Connect is called again
     */
    StateFailed = "failed",
};

/**
 * Message is one received (or echoed) publish.
 * Payload is []byte on purpose: the frontend decides how to render it.
 * Wails serialises it as base64; the frontend decodes it once in api.ts.
 */
export interface Message {
    /**
     * monotonic per session, used as list key and for dedupe
     */
    "id": number;
    "profileId": string;
    "topic": string;
    "payload": string | null;
    "qos": QoS;
    "retained": boolean;
    "receivedAt": string;
    "props": Properties;
}

/**
 * MessagesBatch is emitted at most every 50 ms per session (see batcher.go)
 * and only contains messages on topics the UI is watching. Dropped > 0 means
 * the batcher's pending queue overflowed between ticks, i.e. the UI really did
 * not see those messages in the stream (they may still be in history).
 */
export interface MessagesBatch {
    "profileId": string;
    "seq": number;
    "messages": Message[] | null;
    "dropped": number;
}

/**
 * Properties is the MQTT 5 subset worth showing in the inspector.
 * All fields optional; zero value means "absent".
 */
export interface Properties {
    "contentType"?: string;
    "responseTopic"?: string;
    "correlationData"?: string | null;

    /**
     * seconds
     */
    "messageExpiry"?: number | null;
    "user"?: { [_ in string]?: string } | null;
}

/**
 * Publish is what the UI sends. Kept separate from Message so the
 * publish bar can't accidentally carry received-only fields.
 */
export interface Publish {
    "topic": string;
    "payload": string | null;
    "qos": QoS;
    "retain": boolean;
    "props": Properties;
}

export enum QoS {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    QoS0 = 0,
    QoS1 = 1,
    QoS2 = 2,
};

/**
 * SessionSnapshot is everything the UI needs to render one session from
 * scratch, consistent as of Seq.
 */
export interface SessionSnapshot {
    "profileId": string;
    "seq": number;
    "state": ConnState;
    "error"?: string;
    "subscriptions": Subscription[] | null;
    "topics": TopicStats[] | null;
}

export interface StateChanged {
    "profileId": string;
    "seq": number;
    "state": ConnState;

    /**
     * populated for Failed / Reconnecting
     */
    "error"?: string;
    "at": string;
}

export interface Subscription {
    /**
     * may contain + and #
     */
    "filter": string;
    "qos": QoS;
}

export interface SubscriptionsChanged {
    "profileId": string;
    "seq": number;
    "active": Subscription[] | null;
}

/**
 * TopicStats is one node in the topic tree. Path is the full topic;
 * the frontend derives the hierarchy by splitting on '/'.
 */
export interface TopicStats {
    "path": string;
    "count": number;
    "bytes": number;
    "lastSeen": string;
    "retained": boolean;

    /**
     * LastPayload is the newest payload truncated to PreviewBytes, so the
     * tree can show a value next to every topic without watching it.
     */
    "lastPayload": string | null;

    /**
     * AvgInterval is a smoothed gap between consecutive messages in seconds
     * (0 until a topic has seen two). The UI uses it to flag topics that
     * have gone quiet for much longer than usual.
     */
    "avgInterval": number;
}

/**
 * TopicsChanged carries only the delta since the last tick.
 */
export interface TopicsChanged {
    "profileId": string;
    "seq": number;
    "upserts": TopicStats[] | null;

    /**
     * full paths, e.g. after a clear
     */
    "removed": string[] | null;
}

/**
 * WatchResult is the history of one topic at the moment the UI started
 * watching it, newest first. Live batches follow; the frontend reconciles
 * the two by message ID alone (every later message has a larger ID), so
 * no Seq is needed here.
 */
export interface WatchResult {
    "profileId": string;
    "topic": string;
    "messages": Message[] | null;
}
